### PR TITLE
Support installing plugin from custom source

### PR DESCRIPTION
**Pull request by miguelaferreira**
The `vagrant_plugin` provider supports installing from a custom source. This PR adds that possibility to the `install_plugins` recipe

### CODE REVIEW

**Comment by jtimberman** [comment]
I'll review this and other PRs/issues in this repository next week. I've been out on vacation and then the Chef summit the last couple weeks. :ice_cream:

**Comment by dougireton** [comment]
I'm working on this. I'm writing a failing spec first.

**Comment by dougireton** [comment]
@miguelaferreira I'd like to understand your use case a bit better. Are you trying to specify a vagrant plugin on disk, or at a custom https:// location?

There seem to be issues with the way Vagrant handles `--plugin-source` locations. This is from the Vagrant docs:

```
--plugin-source SOURCE - Adds a source from which to fetch a plugin. Note that this doesn't only affect the single plugin being installed, by all future plugins as well. This is a limitation of the underlying plugin installer Vagrant uses.
```

[See this Vagrant issue](https://github.com/mitchellh/vagrant/issues/4486).
Also, [see this StackOverflow question](http://stackoverflow.com/questions/17028132/vagrant-install-plugin-from-github).

**Comment by miguelaferreira** [comment]
I was planning to point the source to an http url. But from disk would work too.

Reading the snippet from the vagrant docs, I'm guessing that spectrograph a source is a bad idea. However, I've installed custom builds of variant plugins from disk by specifying a file name. An example would be:
vagrant plugin install vagrant-cloudstack-1.0.0.gem

**Comment by dougireton** [comment]
This PR is superceded by PR #48.

**Pull request closed without merging**
